apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-java-app
  labels:
    component: simple-java-app
spec:
  selector:
    matchLabels:
      component: simple-java-app
  template:
    metadata:
      labels:
        component: simple-java-app
    spec:
      containers:
        - name: simple-java-app
          image: hamer123/simple-java-maven-app
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: simple-java-app-service
  labels:
    component: simple-java-app
spec:
  selector:
    component: simple-java-app
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gateway-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: simple.java.app.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: simple-java-app-service
                port:
                  number: 8080