apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-java-app
  labels:
    component: simple-java-app
spec:
  selector:
    matchLabels:
      component: simple-java-app
  template:
    metadata:
      labels:
        component: simple-java-app
    spec:
      containers:
        - name: simple-java-app
          image: hamer123/simple-java-maven-app
          imagePullPolicy: Always
          ports:
            - containerPort: 8080