apiVersion: v1
kind: Service
metadata:
  name: simple-java-app-service
  labels:
    component: simple-java-app
spec:
  selector:
    component: simple-java-app
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080